import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@repo/ui/styles.css";
import "@repo/ui/types.d.ts";

import "./globals.css";
import SessionProvider from "../context/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>{children}</body>
      </SessionProvider>
    </html>
  );
}
